name: lumenor-website
region: nyc
static_sites:
  - name: lumenor-website
    environment_slug: html
    git:
      repo_clone_url: https://github.com/alsterdev0/lumenor-website.git
      branch: main
    build_command: npm ci && npm run build
    output_dir: dist
    routes:
      - path: /
domains:
  - domain: lumenorlabs.com
    type: PRIMARY
    zone: lumenorlabs.com
    minimum_tls_version: "1.3"
